{ pkgs, ... }: {
	home.packages = [
		pkgs.socat
		pkgs.shotman
		pkgs.wf-recorder
	];
	wayland.windowManager.hyprland = {
		enable = true;
		package = pkgs.hyprland;
		portalPackage = pkgs.xdg-desktop-portal-hyprland;
		xwayland.enable = true;
		settings = {
			autogenerated = 0;
			monitor = "HDMI-A-2, 1920x1080@100, 0x0, 1";
			
			exec-once = [ 
				"hyprpaper"
				"eww open bar"
				"hyprctl setcursor cursor 25"
			];
			
			env = [
			  "XCURSOR_SIZE,24"
			  "HYPRCURSOR_SIZE,24"
			  "QT_QPA_PLATFORMTHEME,qt6ct"
			  "XDG_CURRENT_DESKTOP='Hyprland'"
			  "XDG_SESSION_TYPE='wayland'"
			  "XDG_SESSION_DESKTOP='Hyprland'"
			  "QT_AUTO_SCREEN_SCALE_FACTOR='1'"
			  "QT_QPA_PLATFORM='wayland'"
			  "QT_QPA_PLATFORMTHEME='gtk3'"
			];
			
			windowrule = [
				"noblur, class:firefox, title:firefox"
			];
			
			blurls = "gtk-layer-shell";
			layerrule = [
				"ignorezero, gtk-layer-shell"
			];

			general = {
				gaps_in = 10;
				gaps_out = 30;
				
				"col.active_border" = "rgb(458588) rgb(689d6a) 45deg";
				"col.inactive_border" = "rgb(594945)";
				resize_on_border = true;
				border_size = 2;

				allow_tearing = true;

				layout = "dwindle";
			};
			
			decoration = {
				rounding = 12;
				rounding_power = 2; # НЕ ТРОГАЙ БЛЯДЬ!
				
				active_opacity = 1.0;
				inactive_opacity = 1.0;
				
				shadow = {
					enabled = true;
					range = 10;
					render_power = 3;
					color = "rgb(1d2021)";
				};
				blur = {
					enabled = false;
				};
			};

			animations = {
			  enabled = "yes, please :)";

				bezier = [
					"easeOutQuint,0.23,1,0.32,1"
				  "easeInOutCubic,0.65,0.05,0.36,1"
				  "linear,0,0,1,1"
				  "almostLinear,0.5,0.5,0.75,1.0"
				  "quick,0.15,0,0.1,1"
				];

				animation = [
					"global, 1, 10, default"
					"border, 1, 5.39, easeOutQuint"
					"windows, 1, 4.79, easeOutQuint"
					"windowsIn, 1, 4.1, easeOutQuint, popin 87%"
					"windowsOut, 1, 1.49, linear, popin 87%"
					"fadeIn, 1, 1.73, almostLinear"
					"fadeOut, 1, 1.46, almostLinear"
					"fade, 1, 3.03, quick"
					"layers, 1, 3.81, easeOutQuint"
					"layersIn, 1, 4, easeOutQuint, fade"
					"layersOut, 1, 1.5, linear, fade"
					"fadeLayersIn, 1, 1.79, almostLinear"
					"fadeLayersOut, 1, 1.39, almostLinear"
					"workspaces, 1, 2.5, almostLinear, slide"
					"workspacesIn, 1, 2.5, almostLinear, slide"
					"workspacesOut, 1, 2.5, almostLinear, slide"
				];
			};
			
			dwindle = {
				pseudotile = true;
				preserve_split = true;
			};

			master = {
				new_status = "master"; #Ломастер блять
			};

			misc = {
				force_default_wallpaper = 0;
				disable_hyprland_logo = true;
			};

			input = {
				kb_layout = "us,ru";
				kb_variant = "qwerty";
			  kb_options = "grp:alt_shift_toggle";
			  follow_mouse = 1;
				sensitivity = 0.2;
			};

			gestures = {
				workspace_swipe = false;
			};

			"$mod" = "SUPER";
			
			bindm = [
				"$mod, mouse:272, movewindow"
				"$mod, mouse:273, redizewindow"
			];

			bind = 
			let 
				dir = "/home/chronoblade/nix/homeManager/apps/desktop/windowManagers/hyprland/anotherFiles/rofi/rofi.rasi";
			in [
				"alt, l, exec, eww open lock-dialog"
				"alt, g, exec, eww close bar"
				"alt, m, exec, eww open bar"

				"$mod shift, q, exec, eww open exit-dialog"
				"$mod ctrl, r, exec, eww open reboot-dialog"
				"$mod ctrl, q, exec, eww open off-dialog"
				"alt, l, exec, eww open lock-dialog-zopa"

				"$mod, c, killactive,"
				"$mod, s, togglefloating,"
				"$mod, t, pseudo,"
				"$mod, g, togglesplit"

				"alt, space, exec, rofi -show drun -config ${dir}"

				"$mod, 1, workspace, 1"
				"$mod, 2, workspace, 2"
				"$mod, 3, workspace, 3"
				"$mod, 4, workspace, 4"
				"$mod, 5, workspace, 5"
			  "$mod, 6, workspace, 6"

			  "$mod SHIFT, 1, movetoworkspace, 1"
		    "$mod SHIFT, 2, movetoworkspace, 2"
		  	"$mod SHIFT, 3, movetoworkspace, 3"
		  	"$mod SHIFT, 4, movetoworkspace, 4"
		  	"$mod SHIFT, 5, movetoworkspace, 5"
			  "$mod SHIFT, 6, movetoworkspace, 6"

			  "$mod, mouse_down, workspace, e+1"
			  "$mod, mouse_up, workspace, e-1"
			];
		};
	};
}
